### ISSUE TITLE
Copy image even if game title not found

### ISSUE THREAD

**Issue by prat0088** [RenanGreca/Switch-Screenshots#12]
There is value in copying a game to a destination directory named after its ID.  Presently those files are ignored.  If the user wants to organize them he will need to scroll through potentially hundreds of lines of logs sorted by date, then add the titles to the .json file.  It would be much faster and easier to use if the files were organized to folders he could inspect and rename.  This way he would only need to run the script once and never touch the .json file.

**Comment by RenanGreca** [comment]
I'm adding this functionality in version 2.0.0. Thanks for the feedback!
