### ISSUE TITLE
Couple more game IDs

### ISSUE THREAD

**Issue by gedrick** [RenanGreca/Switch-Screenshots#19]
Hi there - thanks for writing this script!

I have a few more game IDs, all from US territory.

"046C460F6D16A3B4015E1403DA816ECD": "Final Fantasy XII",
"2CC8B772AF83B29364B7B4AD907F1F51": "Final Fantasy XV - Pocket Edition",
"6D311B9F9472ED7110A68EEEFB884101": "Sphinx and the Cursed Mummy",
"8A02A443096C4A41164DDD7DD5CF0967": "Automachef",
"25B77E52575617C0C2E4A4E0A346538C": "Shantae Half Genie Hero",
"69AA450BB058D7C0F3FABB7FC7C2DBA2": "Moonlighter",
"74E60CA799C3278AD6279D11AE5FEBDA": "Onimusha Warlords HD",
"456F2C9BE4E84FE854619AD59C5D00A2": "Yonder - The Cloud Catcher Chronicles",
"692EC865DB8D5C0B5E910C82FDFC2AEC": "Raiden V",
"695E3FE0793D9789A57187ADD7649DCC": "Trine 4 - The Nightmare Prince"

**Comment by RenanGreca** [comment]
Added in commit [20f7747](https://github.com/RenanGreca/Switch-Screenshots/commit/20f774714598f1f8661ad386ea7b54cfc2cfb105).

Thanks for the contribution!
