### ISSUE TITLE
Add Robonauts - Demo

### ISSUE THREAD

**Issue by joogps** [RenanGreca/Switch-Screenshots#20]
I'm manually organizing my Nintendo Switch screenshots, but your index is being very useful for identifying the games, mainly the ones with very few screenshots (mostly demos), so I thought it would be great to help you somehow!

I read it's preferred to write an issue rather than forking the project, so here's the ID I would like to add:

**"D68C79758FC22A7A0BEF5CCBC1F68FF1": "Robonauts - Demo"**

(Also, I think "Resident Evil - Cloud Version" is misspelled as "Resident Evil - Cloud Ver.")

I look forward to contributing more to the project soon! Thanks!

**Comment by joogps** [comment]
(I kinda tried to delete this issue because I thought it wasn't helpful enough. I'll keep it anyway)

**Comment by RenanGreca** [comment]
Thanks João, I added the code to the list :)
