### ISSUE TITLE
Game ID Update

### ISSUE THREAD

**Issue by jackleveledup** [RenanGreca/Switch-Screenshots#21]
Thank you so much for this script, this is perfect. I've been looking into doing a photo journal for my games, and _not knowing_ how to get them organized stalled me out for years. I'm so grateful to be able to dig into it now! Anyway, here are a bunch of game IDs from my captures that weren't picked up in release 2.0.0:

| Game ID | Game Name |
| ------------- | ------------- |
| 0C015090E6C5E3F06D97FEDE95458758 | Luigi's Mansion 3 |
| 0DC6ECE91CF3F6F02BAFC002E3FFBAAD | Fire Emblem: Three Houses |
| 3B527963A4E21EDEF87C54FA5600E205 | Kero Blaster |
| 3C15B8B5FCFF64D185612CFC684FD589 | Okami |
| 3CB55EE215BEA02B113D3BFB17EF3DBA | Dragon Blaze |
| 5F25EBBAB5987964E56ADA5BBDDE9DF2 | Pokémon: Let's Go, Eevee! |
| 6DAE92E255B607316379F3E517CBDFC0 | Marble It Up! |
| 7F84FCDD31F7A57993D7F9D20F9FE46B | Ikaruga |
| 9BB7C01E75A2A0FD6AD24165CAB02257 | Daemon x Machina Demo |
| 36FB9647D509FCDAE5418FF0E8583142 | Gato Roboto |
| 42D51332E98075DFC90EDDCE4B254E8B | The Missing: J.J. Macfield and the Island of Memories |
| 48A5A467593C21DFC93CCCF18D91FCE1 | Collection of Mana |
| 051F2E17E4EB124107ADFF00712F68EA | Katana Zero |
| 67D01338887DAC4477826B5EA75BFB74 | Wizard of Legend |
| 69B9969EC3D9DF6399D6DC160DC26E68 | Phantom Breaker: Battle Grounds Overdrive |
| 71FADCF8929C7E9963F20F9D9728672A | Mega Man 11 |
| 93C1C73A3BAF9123A15B9B24886B634B | Octopath Traveler |
| 0263CFE07655B982D6035111B38E8B72 | Hyrule Warriors: Definitive Edition |
| 372BD77417B847E4D7050826C7C9B60F | Battle Chasers: Nightwar |
| 935E13FC47C481C979FEA5B1CC318284 | Wargroove |
| 64902EF0DF1ABA05E4076CB0BBFCD9A5 | Tales of Vesperia: Definitive Edition |
| 987323D95ADF303B4B8C6E1A0173D61C | Steam World Quest |
| 7806952E0DBDCB5223EC78FF8088406C | Mega Man X: Legacy Collection 1 |
| 9129043EF2AAD7F1157CF852BACB8F7D | The Legend of Zelda: Link's Awakening |
| 9349210FA0267D208CECA1B424DCE082 | Team Sonic Racing |
| A6823431F0DD63EA1A6E9C4B064A7463 | River City Girls |
| B2AA81D02C39303EBD04D8D7F246F34A | Deltarune |
| B8FAEF4816CAC2B76D11869B05CA7601 | Pokémom Shield |
| BA8E0FCB931BBA7F76DCA06732EF9A07 |  Mario Tennis Ace |
| BB59BA50B4B529EC74388B9232DFFE92 | Fe |
| BB94A4F7A98363EA778A47A67857CF7D | Final Fantasy X HD Remaster |
| BD0E7D5235BE8956C727AA4CED0452C7 | Shovel Knight: Specter of Torment |
| BD73E6433C2A382DAEEBE2F64C3DD7DE | Little Town Hero |
| C7C3CAEB6C50DA2C777325EA990171EE | Katamari Damacy Reroll |
| CCFE55975D68069E990E9064D7B828A9 | Cadence of Hyrule |
| D02D58137844CD4B939CD3571BCB8355 | Steam World Heist |
| DE93618DDF64F9184ADD7AEC762AB7EB | Star Ocean: First Departure R |
| E9A2C3977990DCBB13CD00C0F35675FD | Downwell |
| E73E4976CD1992F1CF99AC0053695FD6 | Super Monkey Ball: Banana Blitz HD |
| F9E4ED7281324AE9C62C7E2BBA082F61 | The World Ends With You: Final Remix |
| F95B57762E79CABDA198AE6BBDC6C7D5 | Bloodstained: Ritual of the Night |
| F869F29B8909D93B8F6A1EC5BDDAB49F | Owlboy |
| F639752F5FA028761EF9C25DB534FD07 | Azure Striker Gunvolt: Striker Pack |
| FEDDFB3BEB94843E6A8D2AF517CAE725 | Chocobo's Mystery Dungeon: EVERY BUDDY! |

**Comment by RenanGreca** [comment]
Hi @jackleveledup. Pardon the delay, but I finally added the IDs you sent. Thank you a lot for the contribution.

You can find the updated `game_ids.json` file in the repository.
