### ISSUE TITLE
Going through the json id file, found some games not implemented

### ISSUE THREAD

**Issue by Red-CS** [RenanGreca/Switch-Screenshots#23]
Here are the only 2 I have

- Pokemon Sword {"3C66B776DB1AA06323037049FACD96D3"}
- Xenoblade Chronicles 2: Torna - The Golden Country {"4CBEE39065EC88984BABA68A511DDD19"}

These are both for the North American version (I don't know region details/nomenclature to be more specific. Apologies).

**Comment by RenanGreca** [comment]
I added these to the list. Thanks!
