### ISSUE TITLE
Some extra IDs

### ISSUE THREAD

**Issue by makasenai** [RenanGreca/Switch-Screenshots#24]
So here are the IDs it couldn't identify for me and that are missing from the latest json.

"3C66B776DB1AA06323037049FACD96D3" Pokémon Sword
"1AAFE12FC4DA32AA90B2C527DF73B08B" VOEZ -demo version-
"2D2DD5427221CE0F9F97275FAAF2BD60" DOOM (1993)
"4D37E8E895F61DAB62161ACC7942945A" Membrane
"5A6F3157C944341CDE279FD85822A3AD" Pokkén Tournament DX
"5C78065CD98929D80FE9662AC4A6DDA2" Crypt of the Necrodancer
"5D500549174110191B5A65DD8B17A9E2" Pokémon Let's Go Pikachu/Let's Go Eevee trial version
"5E92066D83C981FCBC05AE4D9711906A" ファミリーコンピュータ Nintendo Switch Online (Famicom/NES, Japanese version)
"9D6B5AFEF371E7D57A4EF29F3A421F7A" Pokémon Home
"54D423DA5645E6DFF84020D96E3F2FEA" Blasphemous Demo
"94385799F4667FC55304697D8F49B8B7" VA-11 HALL-A
"509005580AA0EE52748499526A3C91B9" void tRrLM(); Trial,Ver (Japanese)
"AC0F641AF6D3A018CC6910B1787620CB" ACA NEOGEO Money Puzzle Exchanger
"C392D9DD4226F3430D460A366D67397E" Shipped
"EA525566BC202E51840BCC68D0E37FC9" DOOM 2
"FE6A6449B65FB0A4A26539786A3AA807" Freedom Planet
"FE18FAEF72D654FB0AB3E66905246B60" Cadence of Hyrule -demo version-

**Comment by RenanGreca** [comment]
Thank you for the contribution!
