### ISSUE TITLE
Missing IDs

### ISSUE THREAD

**Issue by sweetpopcorn** [RenanGreca/Switch-Screenshots#26]
The script couldn't find these two IDs. Both are Europe region.

Game ID                                                        | Game Name
-----------------------------------------------------------|------------------------------------------
02CB906EA538A35643C1E1484C4B947D  | Animal Crossing: New Horizons
F8DC9B4C1339AEC598320758EECD69C2 | Warface

**Comment by RenanGreca** [comment]
Added! Thanks!
