### ISSUE TITLE
New ID's

### ISSUE THREAD

**Issue by alexelnintendero** [RenanGreca/Switch-Screenshots#48]
Europe (spain)

0C015090E6C5E3F06D97FEDE95458758 - Luigi's mansion 3
3D8E1DE4D671F7453AFA0C395B825E90 - Clash N'Sane Trilogy
6EDB189E502491BA0A0696C9D03A8FEE - Borderlands 2
7CBCCE282CD36658AB28471FB4791102 - Pokemon Arceus
9A9B6E0371D34263D6B6577F9CBA54D5 - Metroid Dread
33B8CC310F76D76B17C6DB0011A75C8A - New Super Mario Bros U Deluxe
75EA6B6DBAD83649DC8B76075B47ECDA - The Legend of Zelda Skyward Sword HD
76ABD1FB8107400EA366E7B6FBE45ABB - Nintendo Switch Online App
87F15DF5B1168A79BAD3D501C9C0B14D - Borderlands The Pre Sequel
251B606CAAE97CD7BB1849E9DAD12C82 - Rayman Legends
5855558AA8FCD2E87BC21377436CFBF0 - Child of Light
A15180A3520B94075456E9EBE1CD7B71 - Marvel Guardians of the Galaxy
C15A47C7F7B07448C8F2E3BDF73AD439 - Namco Museum
D7BD945BC12F73CA28E54763B2FCE27F - Hyrule Wariors Age of Calamity Demo

**Comment by RenanGreca** [comment]
Thanks, I added them!
