### ISSUE TITLE
New IDs

### ISSUE THREAD

**Issue by Geckobit** [RenanGreca/Switch-Screenshots#51]
Hello, I have found these missing IDs from my screenshots (NA).

- 339470D1C820D6D2392320FD0992BB5E - Pokémon Unite
- A5A477B869AFD225B3DAF74249D70FF2 - Pokémon Mystery Dungeon: Rescue Team DX
- C57722BCA3D76018529DD7D1A46BB144 - Monster Boy and the Cursed Kingdom
- E9FC2E92476F589F890674FE873B0D05 - Mario Party Superstars

**Comment by gamebits** [comment]
The Pokémon and Mario games were eventually added in 26bf272 — thanks!

Monster Boy still remains to be added.
