### ISSUE TITLE
New IDs

### ISSUE THREAD

**Issue by Gwynevera** [RenanGreca/Switch-Screenshots#53]
Thanks for this, I appreciate your efforts!

Here are some IDs from Europe (Spain)
The majority of missing IDs are from demos, so they won't be that useful, really xD

[game_ids.txt](https://github.com/RenanGreca/Switch-Screenshots/files/11581486/game_ids.txt)

**Comment by gamebits** [comment]
Thanks for the submission! When opening issues, it's easiest to submit just the new lines, instead of a complete file. Here are this issue's unique games that are not in the latest JSON file as of 26bf272:

```
  "B14300D92ED6F8D3118E6D3BB07BF40E": "Asphalt 8",
  "C2D43B76F383A86B8EFE30B43FA207C5": "Attack on Titan 2 - Demo",
  "527D63A98D52DBC42C0498FE710B325C": "Dauntless",
  "DFA81AB57355EF9D9827B6FD8A23533B": "Dragon Ball FighterZ",
  "52AEB7EC7AD361B124628FDE71929E05": "Drawn to Life Two Realms",
  "1AB131B6E6571375B79964211BB3F5AE": "Error Overlay",
  "297CCD9310B5A3428DD72E1E8E1DB278": "Kill la Kill IF",
  "09DA83AF74AB162AEE162473AB4C99B6": "Lethal League Blaze - Demo",
  "A72DB9B6A79458E56A0FF3CAA68C7EF4": "Megaman Zero ZX Collection",
  "DA9F3713891E94D55927E9C7825B2A8D": "Megaman 11 - Demo",
  "1CA528593A9112595542B3E5B78510B0": "Mighty Gunvolt Burst",
  "7111B191E2BE628CCF07FC39C001BACE": "Mighty Gunvolt Burst - Demo",
  "69203F57A02BA39D7A6E8912E69294CD": "Minit",
  "856082D450FA5F52542520A9FDF7DCDF": "Oceanhorn - Demo",
  "316BFA7ADD8FAD56FD16235AEE761C70": "Rainworld",
```

Note that "Error Overlay"'s game ID _is_ in the current JSON file, identified as "Nintendo Switch".
