### ISSUE TITLE
.exe version only works for limited games?

### ISSUE THREAD

**Issue by TroytlePower** [RenanGreca/Switch-Screenshots#6]
Hey all!

I've seen that this has had several updates adding games to the .json file, but it seems like the .exe isn't utilizing that updated list? I've tried using the most recent .exe and .json several times, and it's only finding BotW, MK:8, and Switch OS screenshots, despite there being a boatload of screenshots from other games.

Any ideas on how to solve this?

Thanks!

**Comment by RenanGreca** [comment]
Hi! Thanks for using the program.

The .exe version is based on 1.0, which supports screenshots but not video recordings. However, you can make it compatible with all currently supported games by downloading the latest `game_ids.json` file and placing it on the same directory as `organize_screenshots.exe`.

Right now, the latest version of the JSON file is here:
https://github.com/RenanGreca/Switch-Screenshots/releases/download/v1.1.4/game_ids.json

If you have games that are not supported, you can contribute by sending us the _title_ of each game and the _filename_ of one screenshot per game.

I hope this helps! Please let me know if you have more questions.

**Comment by TroytlePower** [comment]
Hmm... still having the same issue. It looks like it might be a chronological issue though. Before 5/12/17, all of my photos were of the three things mentioned (BotW, MK8D, and the Switch OS), and all of those photos got sorted. Then, on 5/12/17, I have a screenshot from Shovel Knight (2017051206091500-F8D087CFC849713C76A06A954E9486D3.jpg), which did not get sorted, nor did *anything* after that image.

I tried deleting that image and running the program again, and it still has the same cutoff as before.

**Comment by RenanGreca** [comment]
That's odd, Shovel Knight was added [quite a while ago](https://github.com/RenanGreca/Switch-Screenshots/commit/9a9a3af555dc8f147dc7f692fdfee22ea3bf166b#diff-b1319aabe52f31d7830582f632701ccd). Did you delete the old version of `game_ids.json` before placing the new one?

**Comment by TroytlePower** [comment]
I did... it definitely seems to be related to Shovel Knight, though. I just deleted the pictures it had sorted, along with the Shovel Knight screenshot, and ran the program again. It pulled a bunch more screenshots this time... right up to the next Shovel Knight screenshot, and then it stopped again.

**Comment by RenanGreca** [comment]
Did it correctly sort any Shovel Knight screenshot?
Could you please send me the filename of one Shovel Knight screenshot?
Which version of Shovel Knight are you playing, Treasure Trove or Spectre of Torment?
In which region did you buy the game?

**Comment by TroytlePower** [comment]
I have Shovel Knight: Treasure Trove from the US eshop. The filename is "2017070619084500-F8D087CFC849713C76A06A954E9486D3.jpg"... I notice that doesn't match what the game_ids file shows, so I tried editing that file with no change (although I may not have done that right).

BTW, thank  you so much for the quick replies! :D :D

**Comment by RenanGreca** [comment]
Odd, it actually does match the ID we already had. The first part of the filename is a timestamp (year, month, day, hour, etc.) and the second is the game's unique ID, in this case `F8D087CFC849713C76A06A954E9486D3`.

Are you having success with other games beyond BotW, MK8D and Shovel Knight?

**Comment by TroytlePower** [comment]
Yeah, once I took the first Shovel Knight screenshots out, it pulled more games (going chronilogically through my screenshots) until it got to another Shovel Knight capture, then stopped.

The json file you linked above has the following:

"Shovel Knight: Treasure Trove",
  "E769E2D93519E8D860445ED00A4A5E3D"

Is it possible that I grabbed the wrong version of the .json file?

**Comment by RenanGreca** [comment]
No, the ID comes immediately before the title, not after. Doing it this way simplified the program logic.

The non-exe version of the program doesn't stop when it encounters an unknown screenshot, just skips over it and leaves a message in the output saying which screenshots were not categorized. I didn't know the .exe behaved that way.

Anyway, I'll check it out this week. That Windows version is long due for an update because of video capture.

**Comment by TroytlePower** [comment]
Oh, I see that now, my mistake!

To be clear, I'm not getting an error or anything, I'm figuring out where it stopped by finding the most recent screenshot it *did* categorize, then going back to find the next screenshot after that one was taken, and in both cases where it got stuck it was Shovel Knight that was up next.

For good news, though... I just removed the next block of Shovel Knight screenshots that it was stuck on and ran it again, and I think it snagged everything else! It looks like I only had ever taken a few screenshots of that game, so getting rid of them wasn't too bad.

Thank you again for your quick replies! This is a great little program, and probably the fastest tech support I've ever received! :D

**Comment by RenanGreca** [comment]
So strange that it's only a problem with Shovel Knight. I'll definitely take a close look at it.

And don't worry about it! This is a program that I made for my own screenshot-organizing problem, and I'm just glad other people are enjoying it!

**Comment by RenanGreca** [comment]
Hello @TroytlePower !

It turns out the issue was with the `:` character in Shovel Knight's title, which caused an error when trying to create its directory.

[Version 1.2.0](https://github.com/RenanGreca/Switch-Screenshots/releases/tag/v.1.2.0) of the program was released, featuring this fix and some other improvements, including support for video captures on the Windows version.

Please let me know if you have any more questions!

**Comment by TroytlePower** [comment]
Fantastic! Now that you say it, it makes sense that that would cause an issue >.> I'll snag 1.2 for future use... thank you again for making this, and for the support!
